### ISSUE TITLE
window not defined error 

### ISSUE THREAD

**Issue by PrasanthGokuldas** [wappsify/react-static-plugin-google-tag-manager#17]
When I run a production build with debug: true, I am getting the below issue.
ReferenceError: Failed exporting HTML for URL shop (__react_static_root__/src/pages/shop/index.js): window is not defined

**Comment by PrasanthGokuldas** [comment]
working fine. with new build.

**Comment by JacquesN16** [comment]
Hi Prasanth! 
Can you share with me how you get this work exactly ? We have met the same problem and I have to put the debug option to false to not get the error. Thank you

**Comment by PrasanthGokuldas** [comment]
its been long time before this issue was posted 1yr back. i think i just deleted the old code and with latest updated code it worked for me.  i tried using yarn too. maybe u can try using yarn instead of npm.
