### ISSUE TITLE
GTM is included twice in built html when debug is true

### ISSUE THREAD

**Issue by karlmacklin** [wappsify/react-static-plugin-google-tag-manager#4]
The generated index.html of our site, when using this plugin, gets the chunk of GTM-code included twice.

Immediately after opening of head tag, and after a larger chunk of our linked stylesheets etc. But not immediately before head close.

When debug is false, it's only include once.

**Comment by wappsify** [comment]
Hey, sorry for the late reply, this should be fixed in the next version!

**Comment by wappsify** [comment]
This should be fixed in version 1.1.2. Thanks for reporting!
