### ISSUE TITLE
GTM is not loaded during "react-static start"

### ISSUE THREAD

**Issue by karlmacklin** [wappsify/react-static-plugin-google-tag-manager#5]
Even when using debug: true the plugin is not used when running `react-static start`.

We would expect the generated HTML to include the snippet in this scenario to be able to debug GTM interactions during development, and not only in production.

**Comment by rori4** [comment]
I have the same issue. The gtm doesn't get injected even if I use ```debug: true```

**Comment by wappsify** [comment]
Hey, this is on purpose actually, but I can give you a config option to allow you to test the snippet locally as well. 👍

**Comment by wappsify** [comment]
Just released v1.1.2 addressing this. When setting `debug` to `true` in the plugin config, the GTM script will now be included in the dev server as well
